language: php
php:
- 7.0
sudo: false
cache:
  directories:
  - node_modules
  - vender
  - $HOME/.composer/cache
services:
- mysql
before_install:
- nvm install 0.12
- nvm use 0.12
install:
- composer install
- npm install
- npm install gulp
- npm install bower
- bower install
before_script:
- mysql -e 'create database braddersrocks;'
- cp  .env.travis .env
- php artisan migrate --seed --force
- php artisan key:generate
script:
- gulp
branches:
  only:
  - master
before_deploy:
- git config --global user.email 'brad.bird.x@gmail.com'
- git config --global user.name 'Brad Bird'
- git add public -f
- git commit -m 'Add build assets'
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: "dexjUZqfgmnT+0OXvG32qqywWOfu2WPea1jAQlvHKZlw6m29GhBEc1RjTH/LyCVdCbLXPKUJk9KJB4Oat9CCxP+bzeszOTuhz3quDXBTLHP5YsCYAx/E5duDYW7yFteFUMW+UdsWbksuXHf4sjmDlirz25+p2naOglMspc7szfjyNCXy4lq5sbKmPgEcjQuFgY0zaXr9QwOwgsManSJegKxhNkbV7PeUmD8aHSLXbweGI0SwqilCjtmdff2lcN4EV6wX1obGJ0nDlaPw9oLL0jx0TFcNd6368HWECbYHwMqwfgngLv9DDv9C5Rs1oS+kBpPEL7OdNq6vBs2Vl51VTFSwUG9LFWO/s+6YAKs91rMp42v0kxCbvMKnkwWmG5gvl/twecfs0CuM835SbcvYzjXCgP0TVBDx95m8E8wFa9pSVRUYYSYAl5er9nvkIBoZHqrq+718n3lkjPrdINOgHXjy6n06fY82CrPVno7ngNZlqXTBY08QYre9PVMqC1BND3zjDPXTsa0tusY4vMDyxmOsTAFUqdljD5uurTV6D83+gWXFNHYehVltWNgP0/VFpZq5bT0CRENrYXCvC+jl6qmq/Qom6I4HTwsS5GR4kBzp0v0mzXVt9z0zMlvbsp6r7ozcDp0lXM5HMRv+0+kueEPXWyTN1vWqPRQ/n3eXQyI="
  strategy: git
  app:
    master: bradders-rocks
  run: php /app/artisan migrate --force
notifications:
  email: brad.bird.x@gmail.com
